# Generated by Django 5.1.6 on 2025-02-13 05:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_servicerequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestattachment',
            name='file',
            field=models.FileField(upload_to=api.models.get_upload_path),
        ),
    ]
